"""add rest days columns

Revision ID: 0e9993e5700c
Revises: 4e4e24cf696d
Create Date: 2026-08-08 20:37:23.410967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e9993e5700c'
down_revision: Union[str, Sequence[str], None] = '4e4e24cf696d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_features', sa.Column('home_rest_days_pre', sa.Integer(), nullable=True))
    op.add_column('match_features', sa.Column('away_rest_days_pre', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_features', 'away_rest_days_pre')
    op.drop_column('match_features', 'home_rest_days_pre')
    # ### end Alembic commands ###
