"""add travel distance column

Revision ID: 127677376388
Revises: f2f7bb862fef
Create Date: 2026-08-10 02:27:58.405486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '127677376388'
down_revision: Union[str, Sequence[str], None] = 'f2f7bb862fef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_features', sa.Column('away_travel_km_pre', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_features', 'away_travel_km_pre')
    # ### end Alembic commands ###
