"""add odds_fetched_at to Match

Revision ID: 22f9986e0c30
Revises: 127677376388
Create Date: 2026-08-15 02:53:25.756877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22f9986e0c30'
down_revision: Union[str, Sequence[str], None] = '127677376388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('odds_fetched_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'odds_fetched_at')
    # ### end Alembic commands ###
