"""add api-football mapping columns and match_stats table

Revision ID: 422db4d88bb9
Revises: 0e9993e5700c
Create Date: 2026-08-09 03:21:21.919359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '422db4d88bb9'
down_revision: Union[str, Sequence[str], None] = '0e9993e5700c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('home_shots_total', sa.Float(), nullable=True),
    sa.Column('away_shots_total', sa.Float(), nullable=True),
    sa.Column('home_possession_pct', sa.Float(), nullable=True),
    sa.Column('away_possession_pct', sa.Float(), nullable=True),
    sa.Column('home_corners', sa.Float(), nullable=True),
    sa.Column('away_corners', sa.Float(), nullable=True),
    sa.Column('home_yellow_cards', sa.Float(), nullable=True),
    sa.Column('away_yellow_cards', sa.Float(), nullable=True),
    sa.Column('home_red_cards', sa.Float(), nullable=True),
    sa.Column('away_red_cards', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id')
    )
    op.add_column('matches', sa.Column('api_football_fixture_id', sa.String(length=50), nullable=True))
    op.add_column('teams', sa.Column('api_football_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'api_football_id')
    op.drop_column('matches', 'api_football_fixture_id')
    op.drop_table('match_stats')
    # ### end Alembic commands ###
