"""add head-to-head columns

Revision ID: 4e4e24cf696d
Revises: ee6a9ba0b39c
Create Date: 2026-08-07 20:22:57.161406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e4e24cf696d'
down_revision: Union[str, Sequence[str], None] = 'ee6a9ba0b39c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_features', sa.Column('h2h_home_ppg_pre', sa.Float(), nullable=True))
    op.add_column('match_features', sa.Column('h2h_away_ppg_pre', sa.Float(), nullable=True))
    op.add_column('match_features', sa.Column('h2h_meetings_pre', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_features', 'h2h_meetings_pre')
    op.drop_column('match_features', 'h2h_away_ppg_pre')
    op.drop_column('match_features', 'h2h_home_ppg_pre')
    # ### end Alembic commands ###
