"""add rolling shots/possession/corners columns

Revision ID: 543a0de146ac
Revises: 422db4d88bb9
Create Date: 2026-08-09 16:12:50.072223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '543a0de146ac'
down_revision: Union[str, Sequence[str], None] = '422db4d88bb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_features', sa.Column('home_shots_avg_pre', sa.Float(), nullable=True))
    op.add_column('match_features', sa.Column('away_shots_avg_pre', sa.Float(), nullable=True))
    op.add_column('match_features', sa.Column('home_possession_avg_pre', sa.Float(), nullable=True))
    op.add_column('match_features', sa.Column('away_possession_avg_pre', sa.Float(), nullable=True))
    op.add_column('match_features', sa.Column('home_corners_avg_pre', sa.Float(), nullable=True))
    op.add_column('match_features', sa.Column('away_corners_avg_pre', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_features', 'away_corners_avg_pre')
    op.drop_column('match_features', 'home_corners_avg_pre')
    op.drop_column('match_features', 'away_possession_avg_pre')
    op.drop_column('match_features', 'home_possession_avg_pre')
    op.drop_column('match_features', 'away_shots_avg_pre')
    op.drop_column('match_features', 'home_shots_avg_pre')
    # ### end Alembic commands ###
