"""add injury and suspension match features

Revision ID: 5f6a75d29be7
Revises: 740ec4f95768
Create Date: 2026-08-09 21:23:28.632020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f6a75d29be7'
down_revision: Union[str, Sequence[str], None] = '740ec4f95768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_features', sa.Column('home_injuries_count_pre', sa.Integer(), nullable=True))
    op.add_column('match_features', sa.Column('away_injuries_count_pre', sa.Integer(), nullable=True))
    op.add_column('match_features', sa.Column('home_suspensions_count_pre', sa.Integer(), nullable=True))
    op.add_column('match_features', sa.Column('away_suspensions_count_pre', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_features', 'away_suspensions_count_pre')
    op.drop_column('match_features', 'home_suspensions_count_pre')
    op.drop_column('match_features', 'away_injuries_count_pre')
    op.drop_column('match_features', 'home_injuries_count_pre')
    # ### end Alembic commands ###
