"""add league position columns

Revision ID: 6b5d043be924
Revises: 543a0de146ac
Create Date: 2026-08-09 16:34:21.670320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b5d043be924'
down_revision: Union[str, Sequence[str], None] = '543a0de146ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_features', sa.Column('home_position_pre', sa.Integer(), nullable=True))
    op.add_column('match_features', sa.Column('away_position_pre', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_features', 'away_position_pre')
    op.drop_column('match_features', 'home_position_pre')
    # ### end Alembic commands ###
