"""add injuries_fetched_at and Injury.match_id

Revision ID: 740ec4f95768
Revises: 6b5d043be924
Create Date: 2026-08-09 21:22:03.707833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '740ec4f95768'
down_revision: Union[str, Sequence[str], None] = '6b5d043be924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('injuries', sa.Column('match_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'injuries', 'matches', ['match_id'], ['id'])
    op.add_column('matches', sa.Column('injuries_fetched_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'injuries_fetched_at')
    op.drop_constraint(None, 'injuries', type_='foreignkey')
    op.drop_column('injuries', 'match_id')
    # ### end Alembic commands ###
