"""add bets table

Revision ID: a48fee1fd1ff
Revises: 22f9986e0c30
Create Date: 2026-08-15 21:57:56.816539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a48fee1fd1ff'
down_revision: Union[str, Sequence[str], None] = '22f9986e0c30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=1), nullable=False),
    sa.Column('stake', sa.Float(), nullable=False),
    sa.Column('odds_taken', sa.Float(), nullable=False),
    sa.Column('bookmaker', sa.String(length=50), nullable=False),
    sa.Column('model_prob_at_bet', sa.Float(), nullable=False),
    sa.Column('ev_at_bet', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'WON', 'LOST', 'VOID', name='betstatus'), nullable=False),
    sa.Column('profit_loss', sa.Float(), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bets')
    # ### end Alembic commands ###
