"""add form columns to match_features

Revision ID: b0b7d2ceb51b
Revises: 8f8fd2accead
Create Date: 2026-08-04 18:33:19.755742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0b7d2ceb51b'
down_revision: Union[str, Sequence[str], None] = '8f8fd2accead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_features', sa.Column('form_home_pre', sa.Float(), nullable=True))
    op.add_column('match_features', sa.Column('form_away_pre', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_features', 'form_away_pre')
    op.drop_column('match_features', 'form_home_pre')
    # ### end Alembic commands ###
