"""add goals scored/conceded columns

Revision ID: ee6a9ba0b39c
Revises: f07e83ab84a9
Create Date: 2026-08-07 20:04:10.749081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee6a9ba0b39c'
down_revision: Union[str, Sequence[str], None] = 'f07e83ab84a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_features', sa.Column('home_goals_scored_avg_pre', sa.Float(), nullable=True))
    op.add_column('match_features', sa.Column('home_goals_conceded_avg_pre', sa.Float(), nullable=True))
    op.add_column('match_features', sa.Column('away_goals_scored_avg_pre', sa.Float(), nullable=True))
    op.add_column('match_features', sa.Column('away_goals_conceded_avg_pre', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_features', 'away_goals_conceded_avg_pre')
    op.drop_column('match_features', 'away_goals_scored_avg_pre')
    op.drop_column('match_features', 'home_goals_conceded_avg_pre')
    op.drop_column('match_features', 'home_goals_scored_avg_pre')
    # ### end Alembic commands ###
