"""add venue-specific form columns

Revision ID: f07e83ab84a9
Revises: b0b7d2ceb51b
Create Date: 2026-08-04 18:53:46.707643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f07e83ab84a9'
down_revision: Union[str, Sequence[str], None] = 'b0b7d2ceb51b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_features', sa.Column('home_venue_form_pre', sa.Float(), nullable=True))
    op.add_column('match_features', sa.Column('away_venue_form_pre', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_features', 'away_venue_form_pre')
    op.drop_column('match_features', 'home_venue_form_pre')
    # ### end Alembic commands ###
