"""add rolling cards columns

Revision ID: f2f7bb862fef
Revises: 5f6a75d29be7
Create Date: 2026-08-09 22:02:39.705853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2f7bb862fef'
down_revision: Union[str, Sequence[str], None] = '5f6a75d29be7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_features', sa.Column('home_yellow_cards_avg_pre', sa.Float(), nullable=True))
    op.add_column('match_features', sa.Column('away_yellow_cards_avg_pre', sa.Float(), nullable=True))
    op.add_column('match_features', sa.Column('home_red_cards_avg_pre', sa.Float(), nullable=True))
    op.add_column('match_features', sa.Column('away_red_cards_avg_pre', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_features', 'away_red_cards_avg_pre')
    op.drop_column('match_features', 'home_red_cards_avg_pre')
    op.drop_column('match_features', 'away_yellow_cards_avg_pre')
    op.drop_column('match_features', 'home_yellow_cards_avg_pre')
    # ### end Alembic commands ###
